import Image from "next/image";
import getStripe from "@/utils/get_stripe";
import { SignIn,SignedOut,UserButton } from "@clerk/nextjs";
import { AppBar, Container, Toolbar, Typography } from "@mui/material";
export default function Home() {
  <Container maxWidth="lg">
      <head>
        <title>
         Flashcard SaaS
         </title>
    <meta name="description" content="Generated by create next app" />
    </head>
    <AppBar position="static">
      <Toolbar>
        <Typography variant="h6">Flashcars Saas
        </Typography>
      </Toolbar>
    </AppBar>
    </Container>
  }

